### ISSUE TITLE
Tag latest not found in repository docker.io/tavk/esp-sdk

### ISSUE THREAD

**Issue by zoutepopcorn** [T-vK/docker-esp-sdk#3]
I'm a Docker noob, but the pull command did not work for me.

```
$ sudo docker pull tavk/esp-sdk
Using default tag: latest
Pulling repository docker.io/tavk/esp-sdk
Tag latest not found in repository docker.io/tavk/esp-sdk
```

After that I used:
```
sudo docker pull tavk/esp-sdk:0.1.0
```

That was working for me.

**Comment by T-vK** [comment]
Oh, you are right. I must have forgotten to push tagged as latest. 
Well, my Internet currently sucks pretty badly so I'll just change the readme files to use 0.1.0

Thanks for reporting!
